<!-- vendor css -->
<link href="<?php echo THEMES_DEFAULT_URL ?>/lib/font-awesome/css/font-awesome.css" rel="stylesheet">
<link href="<?php echo THEMES_DEFAULT_URL ?>/lib/Ionicons/css/ionicons.css" rel="stylesheet">
<link href="<?php echo THEMES_DEFAULT_URL ?>/lib/chartist/css/chartist.css" rel="stylesheet">
<link href="<?php echo THEMES_DEFAULT_URL ?>/lib/rickshaw/css/rickshaw.min.css" rel="stylesheet">

<!-- Slim CSS -->
<link rel="stylesheet" href="<?php echo THEMES_DEFAULT_URL ?>/css/slim.css">


<!-- plugins -->
<link rel="stylesheet" href="<?php echo PLUGINS_URL; ?>jquery.growl/css/jquery.growl.css" />
<link rel="stylesheet" href="<?php echo PLUGINS_URL; ?>ladda/css/ladda.min.css" />
<link rel="stylesheet" href="<?php echo PLUGINS_URL; ?>aos/aos.css" />
<!-- sweet alert -->
<script type='text/javascript' src="<?php echo PLUGINS_URL; ?>swal/sweet_alert.min.js?v=<?php echo $version ?>"></script>

<link rel="stylesheet" href="<?php echo THEMES_DEFAULT_URL ?>css/custom-bootstrap-margin-padding" type="text/css">
<link rel="stylesheet" href="<?php echo THEMES_DEFAULT_URL ?>css/spacing-and-height.css" type="text/css">
<link rel="stylesheet" href="<?php echo THEMES_DEFAULT_URL ?>css/custom.css?v=<?php echo rand() ?>" type="text/css">