<script src="<?php echo THEMES_DEFAULT_URL ?>/lib/jquery/js/jquery.js"></script>
<script src="<?php echo THEMES_DEFAULT_URL ?>/lib/popper.js/js/popper.js"></script>
<script src="<?php echo THEMES_DEFAULT_URL ?>/lib/bootstrap/js/bootstrap.js"></script>
<script src="<?php echo THEMES_DEFAULT_URL ?>/lib/jquery.cookie/js/jquery.cookie.js"></script>
<script src="<?php echo THEMES_DEFAULT_URL ?>/lib/chartist/js/chartist.js"></script>
<script src="<?php echo THEMES_DEFAULT_URL ?>/lib/d3/js/d3.js"></script>
<script src="<?php echo THEMES_DEFAULT_URL ?>/lib/rickshaw/js/rickshaw.min.js"></script>
<script src="<?php echo THEMES_DEFAULT_URL ?>/lib/jquery.sparkline.bower/js/jquery.sparkline.min.js"></script>

<script src="<?php echo THEMES_DEFAULT_URL ?>/js/ResizeSensor.js"></script>
<script src="<?php echo THEMES_DEFAULT_URL ?>/js/dashboard.js"></script>
<script src="<?php echo THEMES_DEFAULT_URL ?>/js/slim.js"></script>

<!-- plugins -->
<script src="<?php echo PLUGINS_URL ?>autosize.min.js"></script>
<script type='text/javascript' src='<?php echo PLUGINS_URL; ?>jquery.growl/js/jquery.growl.js'></script>
<script type="text/javascript" src="<?php echo PLUGINS_URL; ?>ladda/js/spin.min.js"></script>
<script type="text/javascript" src="<?php echo PLUGINS_URL; ?>ladda/js/ladda.min.js"></script>
<script type="text/javascript" src="<?php echo PLUGINS_URL; ?>aos/aos.js"></script>
<script type="text/javascript" src="<?php echo PLUGINS_URL; ?>initial.js"></script>
<!-- sweet alert -->
<link rel="stylesheet" type="text/css" href="<?php echo PLUGINS_URL ?>swal/sweetalert.css?v=<?php echo $version ?>">
<link rel="stylesheet" type="text/css" href="<?php echo PLUGINS_URL ?>swal/themes/google/google.css?v=<?php echo $version ?>">

<!-- custom -->
<script src="<?php echo THEMES_DEFAULT_URL ?>js/formvalidation.js?v=<?php echo rand() ?>"></script>